### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by sparcut** [mjbvz/vscode-github-markdown-preview-style#10]
Add support for emojis as per GitHub flavoured markdown.

https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf (Bottom of page 2)

GitHub follow this standard: WebpageFX/emoji-cheat-sheet.com

They have a few libs for node.js that parse these emojis but they don't seem to be regularly maintained.

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji

**Comment by sparcut** [comment]
Alright, however, it might be wise to add that as dep. to this, as emojis are part of GitHub flavored markdown.
