### ISSUE TITLE
Preview no longer has a margin visible.

### ISSUE THREAD

**Issue by Icexist** [mjbvz/vscode-github-markdown-preview-style#104]
VSCode 1.77.3 on Windows 10. Any other markdown extensions disabled.

No margins are visible when previewing a markdown file. Was working just fine a couple days ago.

![image](https://user-images.githubusercontent.com/5529540/233170572-76f88371-9af7-44f4-8f01-7cb99b5da430.png)

**Comment by mjbvz** [comment]
What version of the extension are you using?

**Comment by Icexist** [comment]
v2.0.1

**Comment by mjbvz** [comment]
Thanks for confirming. Should be published in the marketplace as 2.0.2
