### ISSUE TITLE
Preview not updating live

### ISSUE THREAD

**Issue by Supremekirb** [mjbvz/vscode-github-markdown-preview-style#114]
When opening a preview of a markdown file (Ctrl+K, V), it won't be updated in real-time like it is normally. Additionally, the opened tab is titled `Preview: 'Preview: '[file]''`, when normally it would be `Preview: '[file]'`.

Everything works as intended after disabling the extension and reloading. I am on Windows, using the latest VSCode and latest extension version.

![image](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/99102603/6620c331-c1b0-42fb-8a60-026518000615)

**Comment by Supremekirb** [comment]
Aside from themes:

- .NET Runtime Install Tool
- C/C++
- C#
- CoilSnake
- Debugger for Java
- Deno
- Extension Pack for Java
- GitHub Copilot
- IntelliCode
- IntelliCode API Usage Examples
- isort
- json
- Jupyter
- Jupyter Cell Tags
- Jupyter Keymaps
- Jupyter Notebook Renderers
- Jupyter Slide Show
- Language Support for Java(TM) by Red Hat
- Makefile Tools
- Maven for Java
- Node.js Modules Intellisense
- Pylance
- Python
- WSL

**Comment by mjbvz** [comment]
Did you try disabling all other extensions?

**Comment by Supremekirb** [comment]
I have tried this and there is some strange behaviour. For a little while after disabling extensions (apparently not tied to reloading VS Code), they'll still open as previews of previews, before becoming normal previews again. Then as soon as I reenable extensions it goes back to being a preview of a preview.

**Comment by mjbvz** [comment]
I'm pretty sure this is caused by another extension. This extension only builds on VS Code's existing markdown preview. It does not implement the preview itself
