### ISSUE TITLE
Can we have footnote support?

### ISSUE THREAD

**Issue by aybe** [mjbvz/vscode-github-markdown-preview-style#118]
Here it works:

Testing a footnote[^1].

[^1]: abcdefgh

But not in VSCode:

<img width="132" alt="image" src="https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/1537591/3d6cf94e-b620-48c5-93b5-43f96e3d80e7">

```
Testing a footnote[^1].

[^1]: abcdefgh

```

Thanks! 😁

**Comment by jjspace** [comment]
There is another extension that already provides this capability: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes

Better yet you may want to install this whole extension pack to mimic Github more closely: https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview

**Comment by aybe** [comment]
Perfect, thank you!
