### ISSUE TITLE
Note, warning and important blocks not styled

### ISSUE THREAD

**Issue by DUB1401** [mjbvz/vscode-github-markdown-preview-style#119]
Recently, GitHub added a new format for attention-grabbing blocks. You can read about it [here](https://github.com/orgs/community/discussions/16925).

But at the moment there is no support for such formatting in VS Code, as well as in your extension.

```
> [!NOTE]  
> Sometext.
```

![image](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/40277356/7a314cd8-d1ab-4cef-9113-aaf215308036)

Please integrate this syntax in your extension.

> [!NOTE]  
> Sometext.

**Comment by jjspace** [comment]
Duplicate of https://github.com/mjbvz/vscode-github-markdown-preview/issues/23

**Comment by DUB1401** [comment]
Duplicated.
