### ISSUE TITLE
Handling double square brackets in code block

### ISSUE THREAD

**Issue by eoehm** [mjbvz/vscode-github-markdown-preview-style#128]
The following markdown:

<code>This is in double square brackets: \[\[hello world\]\]</code>

shows properly in GitHub Preview but in VS Code preview, it shows the bracketed part as "undefined":

<code>This is in double square brackets: undefined</code>

**Comment by jjspace** [comment]
![2024-01-16_12-19](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/8007967/ddfecaa1-a9d9-4245-a06d-7856c205411d)

I can't reproduce this. I'd suggest you check what other extensions you have installed and see if one of them is trying to replace double bracket style links.
