### ISSUE TITLE
Light theme can't see code body, terrible!

### ISSUE THREAD

**Issue by blaoke** [mjbvz/vscode-github-markdown-preview-style#131]
![2024-03-11 16-36-27 的屏幕截图](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/35526961/81824b33-e7ed-48ec-bbe2-375c278c8e22)
Look this picture, My theme is light, but the font of some codes in the picture is too shallow, which makes it difficult to see clearly, which is too uncomfortable to see, and I don't want to change the theme to dark. How can I solve this problem?

**Comment by mjbvz** [comment]
Please share the markdown text, vscode version, and extension version

**Comment by blaoke** [comment]
Markdown text likes  below picture
![2024-03-12 09-31-17 的屏幕截图](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/35526961/6e80e2ab-8754-402f-90ac-b890537eba69)

- VSCode Version: 1.87.1
- Markdown-preview-github-styles Version: v2.0.3

By the way, I'm not install theme extentions like one-dark, my vscode theme is  `Default Dark+`

**Comment by mjbvz** [comment]
As text please

**Comment by jjspace** [comment]
@mjbvz I opened a quick PR for it, #132 

Minimal code that reproduces it:

```cpp
#include <cstdin>

int main () {
  int x = 0;
  std::thread t1(inc, std::ref(x), 1);
  std::thread t2(inc, std::ref(x), 2);
  std::thread t3(inc, std::ref(x), 3);
  std::thread t4(inc, std::ref(x), 4);
}
```

**Comment by blaoke** [comment]
@jjspace How can I test these changes in my environment to make sure these changes really fix the problem, and will a new version be released?
