### ISSUE TITLE
LaTeX does not render when in ```math block

### ISSUE THREAD

**Issue by alnoki** [mjbvz/vscode-github-markdown-preview-style#133]
Per the [GitHub docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) a markdown document can include LaTeX in display mode via:

```md
    ```math
    ... LaTeX ...
    ```
```

However this is not replicated in VS Code. Example: https://github.com/econia-labs/econia-v5/blob/5faac14e705d06377241c8d1afed91348770fca3/src/move/research/uniswap-v3-book-milestone-1/README.md

**Comment by mjbvz** [comment]
This was fixed upstream by https://github.com/microsoft/vscode/pull/219820
