### ISSUE TITLE
Update to 2.0.4 breaks the collaboration with yahyabatulu.vscode-markdown-alert

### ISSUE THREAD

**Issue by wytsai7660** [mjbvz/vscode-github-markdown-preview-style#134]
Before 2.0.4 (here 2.0.3):

<img width="1582" alt="Screenshot 2024-03-27 at 13 59 16" src="https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/116703995/b8779c60-a355-44b1-b45c-f4c2b2b47463">

2.0.4:

<img width="1582" alt="Screenshot 2024-03-27 at 13 59 47" src="https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/116703995/d7b86d6b-434f-49de-88c7-65655d6c7c35">

Sorry for using a Mandarin document for demonstration. I only found this feature used in this file.

**Comment by mjbvz** [comment]
This should likely start on `yahyabatulu.vscode-markdown-alert` as this extension does not officially support them
