### ISSUE TITLE
Emoji aren't working

### ISSUE THREAD

**Issue by octref** [mjbvz/vscode-github-markdown-preview-style#14]
Have a markdown like :warning:. The preview does not show it.

**Comment by mjbvz** [comment]
https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji

**Comment by octref** [comment]
Can we possibly add links to your MD contributing extensions at https://code.visualstudio.com/docs/languages/markdown

It's too much hurdle for users to jump through to find either this extension or the emoji extension.
