### ISSUE TITLE
Extension no longer work in VS Code 1.21.0

### ISSUE THREAD

**Issue by benc-uk** [mjbvz/vscode-github-markdown-preview-style#16]
The extension no longer works since updating VS Code to 1.21.
The preview window is shown in the default style (in my case dark) and not with GitHub styling.

I can see no errors in the output logs or the dev console

**Comment by mjbvz** [comment]
Duplicate of #15

**Comment by benc-uk** [comment]
Ok looks like a issue with vs code itself. That's a shame. I'll wait for a fix
