### ISSUE TITLE
Pluggin do not work anymore

### ISSUE THREAD

**Issue by transit-ericmckay** [mjbvz/vscode-github-markdown-preview-style#18]
It is possible that the pluggin don't work with 1.21.0 Version of VSCode?

![image](https://user-images.githubusercontent.com/36936972/37292539-699c35f0-25e7-11e8-83b4-06f9b3d12879.png)

**Comment by glennsarti** [comment]
Same here.  The preview styling has revertted back to "vanilla" VS Code styling.  I have the same version of VSCode.

Windows 10 (1709)

**Comment by glennsarti** [comment]
I assume this fix is required?
https://github.com/Microsoft/vscode/commit/ccc8f5ab36b3d27ed81ff72d03d6ccbc53214ae4

**Comment by linuxiamo** [comment]
... and so, @glennsarti , how do we apply the patch?

**Comment by glennsarti** [comment]
@linuxiamo To be honest, no idea.  Either use the nightly builds of VS Code, or just wait till the next release.  In my case I'm happy to wait, others may be different.

**Comment by glennsarti** [comment]
... and the latest build of VS Code just landed and it's fixed!

![image](https://user-images.githubusercontent.com/5819622/37445230-ab9c572a-2851-11e8-833b-061df89574b8.png)

**Comment by transit-ericmckay** [comment]
Hallelujah! Thanks for sharing!!
