### ISSUE TITLE
Embedded HTML img tag not rendering preview

### ISSUE THREAD

**Issue by dansayo** [mjbvz/vscode-github-markdown-preview-style#19]
my code:

```markdown
table 5 with image.  

| Left-aligned | Center-aligned | Right-aligned |
| :---         |     :---:      |          ---: |
| git status   | git status     | git status    |
| <img src="/images/ss1.png" width="100"> | a sample screenshot      | embedded in a row in the table     |  
```

on Visual Studio preview:
![2018-03-23 11_53_20-chap2 md - gitdocs - visual studio code](https://user-images.githubusercontent.com/29191334/37810761-fad51030-2e90-11e8-99da-d2ff04c5ecdf.png)

on Github:
![2018-03-23 11_55_19-x_mdplay_chap2 md at feature1 internationalriceresearchinstitute_x_mdplay](https://user-images.githubusercontent.com/29191334/37810779-1ab56418-2e91-11e8-9844-fd03aaacd661.png)

**Comment by mjbvz** [comment]
This likely has nothing to do with this extension. What is the folder layout of your workspace? (where is the md file and where is the image)

**Comment by dansayo** [comment]
Images are in the /images path.
The MD file in question is in the /support path.

**Comment by mjbvz** [comment]
Yeah this is unrelated to this extension. I've opened https://github.com/Microsoft/vscode/issues/46448 to track this
