### ISSUE TITLE
Border colors of table cells are overridden by the default style

### ISSUE THREAD

**Issue by yume-chan** [mjbvz/vscode-github-markdown-preview-style#2]
VSCode version: 1.15.0
Extension version: 0.0.2

The border rule at [Line 530](https://github.com/mjbvz/vscode-github-markdown-preview-style/blob/12491ecd7a784a7d24aa08381234af5c56bdbe90/github-markdown.css#L530) is overridden by the default `.vscode-dark table > thead > tr > th { border-color: rgba(255, 255, 255, 0.69); }` and `.vscode-dark table > tbody > tr + tr > td { border-color: rgba(255, 255, 255, 0.18); }` rules, causing the borders are missing.

````
| Column 1 | Column 2 |
|----------|----------|
| Test     | Test     |
| Test     | Test     |
| Test     | Test     |
````

![image](https://user-images.githubusercontent.com/1330321/29208254-eab8c3e8-7ebb-11e7-91df-97867b7bf896.png)

This a easy fix, but I don't know where does your `github-markdown.css` come from, or can I edit it directly.

**Comment by qjebbs** [comment]
I recommend you override it again in `base.css` with `!important`, because github.css is auto generated.
