### ISSUE TITLE
Plugin not working in 1.21.1

### ISSUE THREAD

**Issue by wolf99** [mjbvz/vscode-github-markdown-preview-style#20]
I've just installed this plugin to find that the only thing it appears to do  is add a white background to the markdown preview.

![markdown-test](https://user-images.githubusercontent.com/281700/38258855-75b4cd54-375b-11e8-866d-32e7aebcfccb.png)

![version](https://user-images.githubusercontent.com/281700/38258856-77b332ee-375b-11e8-8c76-02b6d1f6ee0f.png)

Seems like it may be similar to the recent issues with 1.21.0, but those issues are closed as fixed with 1.21.1 and I can't see any way I am not up to date with this.

**Comment by mjbvz** [comment]
Yes this is what it is designed to do (well it also changes the fonts)

If you want task list support, try https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox
