### ISSUE TITLE
YAML front matters are not rendered correctly

### ISSUE THREAD

**Issue by karol-majewski** [mjbvz/vscode-github-markdown-preview-style#23]
Hello and thank you for your work. The issue that I'd like to report has to do with these little snippets located at the top of Markdown files:

```md
---
Name: John
Surname: Doe
---
```

The way GitHub renders them:

![image](https://user-images.githubusercontent.com/20233319/40629922-9068a7d0-62ce-11e8-9210-ef80863a35d5.png)

The way Code does:

![image](https://user-images.githubusercontent.com/20233319/40629953-c11a5bb2-62ce-11e8-8f6a-d525843f62eb.png)

As you can see, the `___` is recognized as a line break prematurely.

**Comment by YuilTripathee** [comment]
same issue here

**Comment by mjbvz** [comment]
For anyone interested in contributing, this plugin may do the job https://www.npmjs.com/package/markdown-it-github-preamble

Here's how it can be contributed: https://code.visualstudio.com/docs/extensionAPI/api-markdown

**Comment by karol-majewski** [comment]
@mjbvz Would you rather like it to become a part of this repository or to exist as a separate extension?

**Comment by mjbvz** [comment]
I just published an extension that adds this: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-yaml-preamble

Currently shipped as its own extension. May consider bundling it as an extension dependency in the future
