### ISSUE TITLE
task lists formatted into negative margin

### ISSUE THREAD

**Issue by diablodale** [mjbvz/vscode-github-markdown-preview-style#26]
Task lists are formatted into the negative margin.

## Repo
```markdown
Below is my list of tasks.

- [ ] test 1
- [ ] test 2 fs sfddsafsdsfg afg afsgfdsg asfgsa afdgafdsgsfdg dfsgdsfg
  sfdg sdfgsdffdsg fda sdf adsfasfas fdsafsadf sadf sadfsadf asdf asf
  saf sadfasdf asdfsadfas fsdafasdf sadfsadf sadfsadf asdfsadf asdf
- [ ] test 3
```

## Errant Result in Preview

![image](https://user-images.githubusercontent.com/679350/41374025-59656396-6f52-11e8-9ae9-0cb73ac06318.png)

## Expected

Here is the GitHub render. Notice the initial sentence and the tasks are left justified to each other.

Below is my list of tasks.

- [ ] test 1
- [ ] test 2 fs sfddsafsdsfg afg afsgfdsg asfgsa afdgafdsgsfdg dfsgdsfg
  sfdg sdfgsdffdsg fda sdf adsfasfas fdsafsadf sadf sadfsadf asdf asf
  saf sadfasdf asdfsadfas fsdafasdf sadfsadf sadfsadf asdfsadf asdf
- [ ] test 3

**Comment by southrop** [comment]
Correct me if I'm wrong, but this issue looks like a duplicate of #13

**Comment by diablodale** [comment]
Agreed. My oversight. Sorry.
