### ISSUE TITLE
Task lists are not rendered with checkboxes

### ISSUE THREAD

**Issue by BrainMaestro** [mjbvz/vscode-github-markdown-preview-style#3]
VSCode version: 1.15.0
Extension version: 0.0.2

![image](https://user-images.githubusercontent.com/1738373/29217815-b73fddf0-7eaa-11e7-9f64-e2f3653d08d9.png)

Great extension, I've always wanted something like this.

**Comment by styfle** [comment]
Like this? https://github.com/mjbvz/vscode-markdown-checkboxes

**Comment by BrainMaestro** [comment]
Yeah pretty much. Can the functionality be merged into this?

**Comment by mjbvz** [comment]
Here's the released extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

I want to keep this extension focused on just styling and not add support for any new markdown syntax. Feel free to put together an extension pack that bundles these together though

**Comment by qjebbs** [comment]
@BrainMaestro I've just published a new ext, added many new syntax  support, including checkbox:

https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended
