### ISSUE TITLE
Dark theme options

### ISSUE THREAD

**Issue by xt0rted** [mjbvz/vscode-github-markdown-preview-style#33]
GitHub Dark has a number of dark themes you can pick from. Would it be possible to include these in the extension? The themes can be found at https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/src/github

**Comment by mjbvz** [comment]
These are good candidate for other extensions. This extension tries to match what a user would see on the standard version of github

**Comment by younesaassila** [comment]
Hi! 👋
Would you mind reconsidering this suggestion now that GitHub has a native dark theme?
Thanks!
