### ISSUE TITLE
Strike through not recognized 

### ISSUE THREAD

**Issue by mullinmax** [mjbvz/vscode-github-markdown-preview-style#38]
`~cross me out~` is not displayed like: ~cross me out~ in the preview

**Comment by mjbvz** [comment]
According to [gfm spec](https://github.github.com/gfm/#strikethrough-extension-), strike through needs two tildes: `~~strike~~` This already works in the VS Code preview.

One tilde works on github but doesn't seem to be documented as officially supported. Doesn't seem worth the effort to support so closing. If someone develops a markdown-it plugin  for this let me know
