### ISSUE TITLE
Syntax Highlight has wrong colors

### ISSUE THREAD

**Issue by octref** [mjbvz/vscode-github-markdown-preview-style#39]
![image](https://user-images.githubusercontent.com/4033249/47944254-a85f4f00-deb7-11e8-8b8c-c6633554cbfb.png)

Compare to GitHub: https://github.com/Microsoft/vscode-docs/blob/ext-docs/api/extension-guides/tree-view.md

![image](https://user-images.githubusercontent.com/4033249/47944308-d6449380-deb7-11e8-86f3-e976963e1601.png)

**Comment by octref** [comment]
@mjbvz Do you wanna try using https://www.npmjs.com/package/shiki to get the same syntax highlighting as VS Code? However we might need to adjust the background color of the code blocks too.

**Comment by mjbvz** [comment]
Ideally this extension should match whatever sytnax highlighting github is using. Looks like something regressed in our highlighting here. I'll take a quick look

shiki would be great as the default for VS Code's markdown preview though. How much big is the bundle?

**Comment by Purpzie** [comment]
![capture](https://user-images.githubusercontent.com/25022704/48920377-2cc14400-ee5e-11e8-9d44-fc3038cc1395.PNG)
Arrow functions seem to be affected the worst.

**Comment by Loilo** [comment]
Quickfix for anybody interested: I collected [a few CSS rules](https://hljs-github-wswafwfpzt.now.sh) that introduce some basic GitHub coloring for Markdown preview code blocks.

It merely gives a similar feeling to the code blocks, there's no way to mirror GitHub behavior with only CSS, as the Markdown Preview's [Highlight.js](https://github.com/highlightjs/highlight.js/) is not nearly as sophisticated as GitHub's [Linguist](https://github.com/github/linguist).

As a little teaser, this is how the code block from the comment above looks in comparison:
<img src="https://user-images.githubusercontent.com/1922624/51763618-48053580-20d3-11e9-820f-c8e9a780c22d.png" alt="The same block of code, compared in GitHub, VS Code and VS Code with custom CSS" width="506" height="585">

To apply these changes to your markdown previews, add the following snippet to your user settings JSON:

```js
"markdown.styles": [
    "https://hljs-github-wswafwfpzt.now.sh"
]
```

**Comment by mjbvz** [comment]
See https://github.com/mjbvz/vscode-markdown-shiki for an example of how we can use a more advanced syntax highlighter + a github color theme 

PRs welcome

**Comment by bLopata** [comment]
@loilo can you help me understand why when I copy your class selectors into my own local css file, I cannot get the styling to apply if I remove `hljs-` from the class name?

**Comment by loilo** [comment]
@bLopata I'm not sure. The styles haven't work for me as well for some weeks or months. Event more annoying, I wasn't able to debug them — devtools don't give any insight into the webviews used by the extension. Not sure whether that was different when I wrote the stylesheet...

**Comment by bLopata** [comment]
@loilo Thanks for the reply. I spent way too long trying to figure out how to apply styles on top of the extension before I found this repo and it using the `.vscode-body-` class. Just to be clear, your classes `.hljs-function` work great in my custom css file imported through  `"markdown.styles": []` in `settings.json`, I was just wondering why I could not get them to work when I removed the prefix. Not a big deal though 🤷‍♂️

**Comment by xt0rted** [comment]
Use the command `Developer: Open Webview Developer Tools` to open a devtools instance for the webview. This is documented [here](https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews) but is hard to find if you're just searching the web for it.

**Comment by SNDST00M** [comment]
This has now been fixed upstream as of `2021-05-15`.
Refs: highlightjs/highlight.js#3191
@mjbvz please update highlight.js to the latest version :)
