### ISSUE TITLE
Odd bug: "*.css" file association sets markdown style back to default

### ISSUE THREAD

**Issue by joslarson** [mjbvz/vscode-github-markdown-preview-style#40]
I've reproduced this bug on macOS and Windows as explained below.

1. Disable all extension except for the "Github Markdown Preview" bundle
2. Remove all custom settings so that your user settings file is as shown below:

```json
{
    "files.associations": {
        "*.css": "scss"
    }
}
```

3. Open a markdown file and launch preview

Following these steps you should see that the markdown preview is using VS Code's default styles, not the Github styles.

If you change "*.css" to anything else ("*.csss" or "*.php" for example) the github markdown styling starts working again.

**Comment by mjbvz** [comment]
Upstream issue https://github.com/Microsoft/vscode/issues/62892

Will move details over

**Comment by mjbvz** [comment]
@joslarson Thank you for the investigation here. I don't think I would have tracked this down otherwise. 

Please try the next VS Code insiders build. It should be fixed in that

**Comment by joslarson** [comment]
@mjbvz glad I could contribute in some way. It took me a while to figure out that it had something to do with my settings file! Thanks for investigating and creating the patch :)
