### ISSUE TITLE
How to get your css file? I want use it somewhere else.

### ISSUE THREAD

**Issue by markwinds** [mjbvz/vscode-github-markdown-preview-style#43]
I am sorry to bother you. I like this style very much, so I want get css file to use it somewhere else. But there are three files like: base.css github-markdown.css  update-github-markdown-css.js. I don't know which file should I take. I'd appreciate it if you could answer that.

**Comment by mjbvz** [comment]
The main css comes from this package: https://www.npmjs.com/package/github-markdown-css

**Comment by markwinds** [comment]
thanks!
