### ISSUE TITLE
Line breaks in HTML exit it while should not

### ISSUE THREAD

**Issue by Xeverous** [mjbvz/vscode-github-markdown-preview-style#45]
Example source file

```html
<table>
<tr>
<th>example</th>
</tr>
<tr>

<td>
<pre>
code
{
        indented code

	indented code after a line break
}
</pre>
</td>

</tr>
</table>
```

Generated preview:

```
code
{
        indented code

 indented code after a line break
}
```

It seems that line breaks between HTML code terminate it completely, the text "indented code after a line break" is not even displayed in monospaced font - after the line break everything is treated as regular markdown text.

The problematic are https://github.github.com/gfm/#html-blocks rule 1 and 6 - line breaks do stop or don't stop HTML depending on how they were opened

**Comment by mjbvz** [comment]
This extension only handles styling the markdown preview, it doesn't change how the markdown is parsed so I don't think this in scope for this extension. If you feel this is an issue with VS Code's markdown parsing/rendering, please file it against VS Code itself
