### ISSUE TITLE
JSX syntax highlighting

### ISSUE THREAD

**Issue by chiangs** [mjbvz/vscode-github-markdown-preview-style#46]
The syntax highlighting for a code fence with type `JSX` does not highlight correctly. Using `HTML` makes it look right, but labeling is incorrect of course.

Syntax highlighting on GitHub supports JSX, and so hopefully this extension can match it.

**Comment by mjbvz** [comment]
Please share some example code

**Comment by chiangs** [comment]
It's possible I either had a syntax error or something else. I'm unable to recreate it now. Sorry about that.
