### ISSUE TITLE
HCL syntax highlighting

### ISSUE THREAD

**Issue by xt0rted** [mjbvz/vscode-github-markdown-preview-style#47]
It doesn't look like the `hcl` language is being colorized in the preview like it is on github.com.

**Sample markup**

```hcl
workflow "Push actions" {
  on = "push"
  resolves = [
    "Install dependencies",
    "Run ESLint"
  ]
}

action "Install dependencies" {
  uses = "docker://node:12-alpine"
  runs = "npm ci"
}

action "Run ESLint" {
  uses = "xt0rted/eslint-action"
  secrets = ["GITHUB_TOKEN"]
}
```

**VSCode preview**

![image](https://user-images.githubusercontent.com/831974/58763456-070da980-8529-11e9-9450-556bd783d1aa.png)

**Comment by xt0rted** [comment]
After looking into this more it seems to be an upstream issue https://github.com/highlightjs/highlight.js/issues/1879

**Comment by mjbvz** [comment]
Closing as upstream
