### ISSUE TITLE
Top margin being applied to first item in the document

### ISSUE THREAD

**Issue by xt0rted** [mjbvz/vscode-github-markdown-preview-style#49]
I'm working on an extension that extends this one and while doing so I noticed all of my `h1` headings had a top margin, while on github.com they didn't.

When using the [this method](https://github.com/mjbvz/vscode-markdown-prism/blob/886380bb63f70c476b0880d277ccbb52a209d087/index.js#L95-L100) of adding an additional style sheet to the document the `style` element is added to the `body` not the `head` which causes the following rule to not apply.

https://github.com/mjbvz/vscode-github-markdown-preview-style/blob/8d4a43c3ccaa9f2e3464cafa251d2e244bc93398/github-markdown.css#L381-L383

Is there another way to add the syntax theme so it goes into the `head` of the document instead of the `body`?

**Comment by mjbvz** [comment]
Have you tried using a [markdown style contribution](https://code.visualstudio.com/api/extension-guides/markdown-extension#changing-the-look-of-the-markdown-preview-with-css) instead?

**Comment by xt0rted** [comment]
I'm using that to add the [GitHub Dark style](#33), but I'm using the code method for the syntax theme since the user can pick which one to use.

**Comment by mjbvz** [comment]
Add it to the end of the html instead?

**Comment by xt0rted** [comment]
That's what I was going to try next, I just wasn't sure if there was a way to get this into the `head` tag via code. I also figured I'd bring up the issue since your Prism extension, if it works with this plugin, will have the same issue.

**Comment by mjbvz** [comment]
Closing this as I think it's out of scope of this extension
