### ISSUE TITLE
Respecting Dark Mode configurations

### ISSUE THREAD

**Issue by nemosmithasf** [mjbvz/vscode-github-markdown-preview-style#50]
Now that VScode supports automatic dark mode adjustment, it would be nice if the plugin can be updated to support the feature as well.

**Comment by mjbvz** [comment]
Out of scope for this extension. Automatic switching to a dark mode goes against the spirit of trying to match how GitHub renders markdown

**Comment by shroudedcode** [comment]
@mjbvz GitHub now has a native dark mode, so maybe it's time to reconsider this? :thinking:

**Comment by mjbvz** [comment]
If someone puts together a PR, then sure

**Comment by shroudedcode** [comment]
@mjbvz I might work on this if I find the time, could you reopen the issue?

**Comment by shroudedcode** [comment]
I just spent some time looking into this and realized that the extension's CSS actually comes from [the `github-markdown-css` package](https://github.com/sindresorhus/github-markdown-css) which has [its own issue for dark mode support](https://github.com/sindresorhus/github-markdown-css/issues/76). I've subscribed to that issue and will look into this again once/if it's resolved.

**Comment by Arka-h** [comment]
@shroudedcode , I just checked the [issue](https://github.com/sindresorhus/github-markdown-css/issues/76) of the [`github-markdown-css`](https://github.com/sindresorhus/github-markdown-css) package, it seems to be resolved and merged, 
It'd be great if you could continue with your work on the dark mode.
