### ISSUE TITLE
Oh My Zsh breaks VS Code markdown preview

### ISSUE THREAD

**Issue by harshal-gajare** [mjbvz/vscode-github-markdown-preview-style#51]
The Extension works great on its own but when I install oh my zsh the Preview for markdown breaks. Any ideas on how to fix that ? 

It seems like the preview is broken the first time , but when I close it and open the preview again things look good.

**Comment by IlanVivanco** [comment]
@harshal-gajare did you do something to fix this? I'm having the same issue, but I'm not sure if Oh my zsh is the culprit.
