### ISSUE TITLE
Dark Themes Dim Preview Text

### ISSUE THREAD

**Issue by macintacos** [mjbvz/vscode-github-markdown-preview-style#52]
When using a light theme, the GitHub preview looks fine:

![image](https://user-images.githubusercontent.com/8128941/81836920-1c999a80-9512-11ea-9346-9c0db7c17cc1.png)

However when I switch to a dark theme, the text become grey and appears "dimmed":

![image](https://user-images.githubusercontent.com/8128941/81836964-2cb17a00-9512-11ea-9407-9ac1b808d76b.png)

Any chance this could be addressed? I don't know what could be causing it, and it doesn't seem limited to the dark theme that I'm using (it happens with all dark themes I have installed, not just the one pictured above). And I can't make heads or tails of what classes are used for the the preview, so I don't know where to start when trying to add my own CSS to fix it.

**Comment by mjbvz** [comment]
See https://github.com/mjbvz/vscode-github-markdown-preview-style/issues/48#issuecomment-627480514

Likely caused by one of your other extensions
