### ISSUE TITLE
Collapsed details sections don't have enough bottom margin

### ISSUE THREAD

**Issue by brianlovin** [mjbvz/vscode-github-markdown-preview-style#53]
Just a small nit, there doesn't seem to be the correct bottom margin applied to collapsed `detail` sections with `summary` previews:

| GitHub.com | Extension |
| ---- | ---- |
| <img width="1071" alt="Screen Shot 2020-07-14 at 12 59 59 PM" src="https://user-images.githubusercontent.com/1923260/87465529-0ff8f780-c5d2-11ea-8bdf-5f06bf711c77.png"> | <img width="918" alt="Screen Shot 2020-07-14 at 1 00 14 PM" src="https://user-images.githubusercontent.com/1923260/87465544-17b89c00-c5d2-11ea-94c8-93152a88ecda.png"> |

**Comment by mjbvz** [comment]
Can you please share the source of the markdown from those screenshots?

**Comment by brianlovin** [comment]
Can't repro any more, maybe something was fixed in the last 1.5 years — thanks for checking!

<img width="926" alt="Screen Shot 2022-01-07 at 14 44 54@2x" src="https://user-images.githubusercontent.com/1923260/148616842-bc447ec1-d09c-4ae1-84c1-ab2e42eeb769.png">
