### ISSUE TITLE
Support dosini code blocks

### ISSUE THREAD

**Issue by Chesare22** [mjbvz/vscode-github-markdown-preview-style#55]
If I have the following md code:
~~~markdown
```dosini
# Inside .env
PORT=9000
```
~~~

In GitHub it renders without any issue:
![image](https://user-images.githubusercontent.com/35499560/87842297-0a6d0d00-c871-11ea-8768-b767e852eda1.png)

But the VSCode preview show this:
![image](https://user-images.githubusercontent.com/35499560/87842223-7307ba00-c870-11ea-9ab8-2737c74eaa44.png)

**Comment by mjbvz** [comment]
The code highlighting is powered by highlight.js. Please file an issue upstream against them
