### ISSUE TITLE
Styling does not work in WSL 2 

### ISSUE THREAD

**Issue by bartdorsey** [mjbvz/vscode-github-markdown-preview-style#56]
When editing a markdown document in WSL 2, the preview window doesn't load the github styles.  I've looked for an error in the logs to see if can figure out why this happens, but I can't find anything. 

![image](https://user-images.githubusercontent.com/362049/89064171-1ce64c80-d32f-11ea-9541-b5ba241c30b1.png)

how it should look (when running locally in Windows without WSL2) 

![image](https://user-images.githubusercontent.com/362049/89064220-34253a00-d32f-11ea-98d2-910cd181e85a.png)

**Comment by bartdorsey** [comment]
I just tried this in VS Code Insider's edition and it works?

**Comment by mjbvz** [comment]
Are you still seeing this

Also be sure to fill in the issue template because I don't know what VS Code version you reported this for /needsMoreInfo

**Comment by bartdorsey** [comment]
Actually this seems to have corrected itself in the last VSCode update.
