### ISSUE TITLE
Markdown Preview is rendered with text full justified (not left justified)

### ISSUE THREAD

**Issue by evanphilipsmith** [mjbvz/vscode-github-markdown-preview-style#57]
Text in the GitHub markdown previews extension is full-justified, not left-justified (like it is on GitHub). Notice the right edge of the block of text.

**Screenshot of GitHub Markdown Preview Style extension in VS Code**
![Screen Shot 2020-09-10 at 6 03 42 PM](https://user-images.githubusercontent.com/12199891/92828201-fe448e00-f38f-11ea-8c68-98a719264ff5.png)

**How GitHub renders the same text**
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus sed vulputate odio ut enim blandit volutpat maecenas. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Id eu nisl nunc mi ipsum faucibus. Id semper risus in hendrerit gravida rutrum quisque. Blandit libero volutpat sed cras ornare. Nibh nisl condimentum id venenatis. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Nisl vel pretium lectus quam id. Eu sem integer vitae justo eget magna fermentum. Enim ut tellus elementum sagittis vitae et. Convallis aenean et tortor at risus. Molestie nunc non blandit massa enim nec dui nunc. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Erat nam at lectus urna duis convallis convallis. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Aliquet lectus proin nibh nisl condimentum. Aliquam ut porttitor leo a diam.

**Comment by Spotnyk** [comment]
FYI: I am not experiencing this issue.

![image](https://user-images.githubusercontent.com/193724/96907414-6c34a880-1458-11eb-9b22-1fe08696c33a.png)
