### ISSUE TITLE
Support for open source versions of VS Code.

### ISSUE THREAD

**Issue by DerekDick** [mjbvz/vscode-github-markdown-preview-style#59]
There are some open source versions of VS Code (like [code](https://www.archlinux.org/packages/?name=code) and [VS Codium](https://aur.archlinux.org/packages/vscodium-bin/) on Arch Linux) that use [the Open VSX registry](https://open-vsx.org/). Please consider uploading this popular extension to OpenVSX :smiley:

[reference](https://wiki.archlinux.org/index.php/Visual_Studio_Code#No_extensions_found)

**Comment by mjbvz** [comment]
I don't have resources to test/support other platforms

**Comment by PeterDaveHello** [comment]
I saw that there's a version that published by @KokaKiwi on 2020: https://open-vsx.org/extension/bierner/markdown-preview-github-styles, not sure if the discussion should be reopen about making it official one or what 🤔
