### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by usernamehw** [mjbvz/vscode-github-markdown-preview-style#65]
GitHub now has official support for 2 themes:

- Default dark
- Dark dimmed

Having at least one of them implemented in this extension (and used if active theme is dark) would be great.

**Comment by kdomke** [comment]
Oh, this would be soooo good.

**Comment by SNDST00M** [comment]
I got this working at https://github.com/OzakIOne/markdown-github-dark/tree/8e173b6

**Comment by mjbvz** [comment]
Want to submit a PR? Seems silly to have two extensions for GitHub styling

**Comment by SNDST00M** [comment]
I absolutely agree, but that other extension is a hack.
I think it's better to wait until Sindre and Hyrious have okayed the upstream issue: sindresorhus/github-markdown-css#76

Afterwards, ozaki's extension could switch to dark-only to differentiate from this extension

**Comment by SNDST00M** [comment]
Yeah Ozaki's extension is dark only. I would suggest to get a fork of https://github.com/hyrious/github-markdown-css/tree/785253e running and help them add a Puppeteer "used CSS" coverage filter.

**Comment by carloswm85** [comment]
> I got this working at https://github.com/OzakIOne/markdown-github-dark/tree/8e173b6
> 
> https://marketplace.visualstudio.com/items?itemName=ozaki.markdown-github-dark

Please, do send a PR. The more people working in the same place, the better.

**Comment by SNDST00M** [comment]
How do people feel about a dark-only or light-only switch on this extension?
This exists on the marketplace already, but Matt's interested in shipping these with the extension.
**React with `👍🏾` if you feel it's useful; react with `👎🏾` if you feel its unneeded.**

**Comment by usernamehw** [comment]
It would make sense if it was an enum with 3 options:

1) Depending on the current theme `workbench.colorTheme` (if theme is dark - preview is dark, if light - preview is light)
2) Dark
3) Light
