### ISSUE TITLE
Tasks list items within <details> tags do not render correctly

### ISSUE THREAD

**Issue by weaversam8** [mjbvz/vscode-github-markdown-preview-style#66]
When rending markdown like this:

```html
<details open>
<summary>Click here to open / close the details view</summary>

- [ ] Task list item
- [ ] Task list item no 2
    - [ ] Task list indented

</details>
```

It should render like this:

<details open>
<summary>Click here to open / close the details view</summary>

- [ ] Task list item
- [ ] Task list item no 2
    - [ ] Task list indented

</details>

But it actually renders like this:

![An image displaying the error described. The "details" element renders correctly, showing a triangle button to open or close the expandable section, but within the expanded section, the task list does not render correctly. It renders as a regular list with bullets instead of checkboxes.](https://user-images.githubusercontent.com/2546219/121422855-a0a09a80-c93d-11eb-9a16-a91d59c66616.png)

**Comment by mjbvz** [comment]
This repo only provides styling, not task list support

Try https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview

**Comment by weaversam8** [comment]
I'm now unable to reproduce this issue, but I only had this extension installed, not the other extensions in the pack.

I believe task list support is provided by VS Code's markdown preview renderer, rather than [`bierner.markdown-checkbox`](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox). We can consider this resolved. If there's another issue, I'll open it with [microsoft/vscode](https://github.com/Microsoft/vscode/issues).

**Comment by mjbvz** [comment]
Great! but just a note that tasklist support does come from extensions and not VS Code itself (I maintain VS Code's builtin markdown preview so I'm pretty confident on this :)

If you see any issues with tasklists, please file them against the extensions
