### ISSUE TITLE
Style Toggle between default and GitHub

### ISSUE THREAD

**Issue by bretonics** [mjbvz/vscode-github-markdown-preview-style#67]
It would be nice to have a settings toggle for this extension that can allow you to temporarily disable the GitHub flavored markdown preview and revert back to the default VS Code one.

**Comment by edward3h** [comment]
Can't you just disable the extension?

**Comment by mjbvz** [comment]
Closing this as out of scope as there is a workaround and there hasn't been further interest expressed in this
