### ISSUE TITLE
Editor moves while typing when preview is open

### ISSUE THREAD

**Issue by BoltonBailey** [mjbvz/vscode-github-markdown-preview-style#71]
When I have the preview open side-by-side with the editor, and I type in the editor, the preview updates live. This is a nice feature, but it seems that because the editor and the preview are linked so that each always scrolls to match the location of the other, when slight changes in the preview change the location of the view of the preview, these cause the markdown editor view to jump around visually, and for me it tends to move the location where I am typing upwards and upwards until it hits the top of the editor. This makes it very hard to see what I am typing.

Perhaps this could be fixed by telling the auto scroll on the editor not to take place unless the user themselves has explicitly scrolled the preview?

**Comment by mjbvz** [comment]
If you are still seeing this issue, please file it against VS Code itself
