### ISSUE TITLE
Inline PDF

### ISSUE THREAD

**Issue by SebDominguez** [mjbvz/vscode-github-markdown-preview-style#72]
I know GitHub doesn't support inline PDF (for reasons)
I'm actually using this markdown preview with my bitbucket repo (and they do support inline PDF)

So it would be amazing if this extension could render the PDF inside the preview window.

```
![Icone exemple](./img/a.svg)
---
![Icone exemple](./img/a.pdf)
```

![Capture d’écran 2021-11-19 à 12 29 24](https://user-images.githubusercontent.com/52816569/142615849-20fdd62e-4479-4040-9eee-1e44cdcb407f.png)
![Capture d’écran 2021-11-19 à 12 29 08](https://user-images.githubusercontent.com/52816569/142616037-526e08af-847a-4bce-ad32-ad11b9a602af.png)

**Comment by mjbvz** [comment]
This extension just contributes the styling (css) for the markdown preview. Adding inline pdf sounds like good candidate for another extension
