### ISSUE TITLE
Markdown preview theme works only when Github theme is active

### ISSUE THREAD

**Issue by chimit** [mjbvz/vscode-github-markdown-preview-style#73]
I'm not sure it's a bug or intended behavior but I'm using the **One Dark Pro** theme and this extension doesn't work properly with it. My markdown previews look like in Github only if I choose the Github official theme (which, of course, is applied to all files - not what I want).

**Comment by Tarocch1** [comment]
To disable One Dark Pro markdown style, add this config to settings.json:

```json
{
  "oneDarkPro.markdownStyle": false
}
```

**Comment by mjbvz** [comment]
Closing this as caused by the One Dark Pro extension
