### ISSUE TITLE
Seems to ignore the trimTrailingWhitespace setting

### ISSUE THREAD

**Issue by sirhaffy** [mjbvz/vscode-github-markdown-preview-style#87]
I have made this settings in 'settings.json' to make VS Code ignore empty lines:

`  
"files.trimTrailingWhitespace": true,
    "[markdown]": {
        "files.trimTrailingWhitespace": false
    }
`
  
  It seems like the plugin ignore this setting, as when I disable the plugin it work again.

**Comment by mjbvz** [comment]
What's the expected behavior?

**Comment by sirhaffy** [comment]
I am very sorry, the problem was in Prettier.
