### ISSUE TITLE
Add Dark-dimmed mode

### ISSUE THREAD

**Issue by jjspace** [mjbvz/vscode-github-markdown-preview-style#89]
This is jumping off #75 as it's own issue. It's much softer on the eyes and the one I use so I was hoping to have VSCode line up with how I see things on GitHub

![2022-05-11_12-48](https://user-images.githubusercontent.com/8007967/167904132-47a0c58d-1920-4718-aa14-781daad84c70.png)

**Comment by mMosiur** [comment]
I agree, I love the dark dimmed GitHub, would be great if the preview could reflect that look
