### ISSUE TITLE
marky-markdown for preview?

### ISSUE THREAD

**Issue by borekb** [mjbvz/vscode-github-markdown-preview-style#9]
Would it be possible to use [marky-markdown](https://github.com/npm/marky-markdown) for preview to achieve closer GitHub parity? The style is very nice but I'm seeing quite a few rendering differences, for example, things that look like URLs are linkified in headings which GitHub doesn't do.

**Comment by mjbvz** [comment]
This would be a better fit for a separate markdown preview extension that provides its own markdown->html engine. This extension just extends VS Code's builtin markdown preview which targets [CommonMark](http://commonmark.org)
