### ISSUE TITLE
Error were shown while trying to load a markdown file or extension resources 

### ISSUE THREAD

**Issue by agamsol** [mjbvz/vscode-github-markdown-preview-style#90]
- I have internet access
- I tried restarting visual studio and also tried to view some other file without success.

_The issue seems to be solved but I decided to post it in a case its a new bug discovered_

**THE ERROR BEFORE VISUAL STUDIO CODE RESTART**
`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

**THE ERROR AFTER VISUAL STUDIO CODE RESTART**
`An error occurred while loading view: markdown.preview`

![ss](https://cdn.agamsol.xyz:90/media/Code_fZOlBJCbdT.png)

**Comment by mjbvz** [comment]
This is a VS Code issue, not an issue with this extension (and its already tracked in the VS Code repo)
