### ISSUE TITLE
Synchronization failing between source and preview -- possible extension conflict?

### ISSUE THREAD

**Issue by dlemire60** [mjbvz/vscode-github-markdown-preview-style#95]
I'm running this extension on VS Code on Windows 10. I'm finding that the preview window is mostly failing to scroll and/or update content to match source changes. If I close the preview tab and re-invoke it, the new display is correct.  I have a number of Matt Bierner's MD-related plugins (Github Markdown Preview, Checkboxes, Emoji, Footnoes, Markdown Preview Github Styling, Markdown Preview Mermaid Support, Markdown yaml Preamble), plus:

 - Code Spell Checker (Street Side Software)
 - Git Graph (mhutchie)
 - Highlight Matching Tag (vincaslt)
 - HTML Preview (George Oliveira)
 - Markdown All In One (Yu Zhang)
 - Markdown Theme Kit (Microsoft)
 - Rewrap (stkb)

I'm wondering if there's a conflict going on.

**Comment by mjbvz** [comment]
Yes I suspect one of the other extensions is causing this. Please give them a test and the file an issue against whichever one is causing the problem
