### ISSUE TITLE
Light theme is badly visible on One Dark Pro theme

### ISSUE THREAD

**Issue by KillWolfVlad** [mjbvz/vscode-github-markdown-preview-style#96]
VS Code settings:

```json
{
  "workbench.colorTheme": "One Dark Pro",
  "markdown-preview-github-styles.colorTheme": "light"
}
```

How it looks:

![image](https://user-images.githubusercontent.com/18448635/210131500-44512696-1e10-4580-a69d-20debc543db0.png)

**Comment by mjbvz** [comment]
One Dark Pro contributes its own markdown styling. Please file an issue against them requesting an option to disable it

**Comment by KillWolfVlad** [comment]
You are right. With settings

```json
{
  "oneDarkPro.markdownStyle": false
}
```

everything looks correct.
