### ISSUE TITLE
Custom user styles not working

### ISSUE THREAD

**Issue by seamusm02** [mjbvz/vscode-github-markdown-preview-style#98]
Create a simple style.css as a test:

`body { background-color: green}`

With extension enabled, the extension overrides the custom style.  With the extension disabled, the style is rendered correctly.

One of the features listed is 
> Customize styling using your own [markdown.styles](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css) css

Am I misunderstanding something?

**Markdown Preview Github Styling** v1.0.1

**VSCode / OS**
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by jjspace** [comment]
It seems that styles are added to the markdown preview in the following order per the [docs](https://code.visualstudio.com/api/extension-guides/markdown-extension#changing-the-look-of-the-markdown-preview-with-css)

- VSCode built in styles
- Extension styles (these ones)
- User styles in `markdown.styles`

However, the way this extension works is it wraps all the rendered markdown content in an extra `div` to be able to specify which theme to use (see img). This is why your style on `body` is being overridden. Change `body` to `.github-markdown-body` and I believe it should work

![2023-03-27_13-55](https://user-images.githubusercontent.com/8007967/228025962-84803d4a-78a7-4c1d-85ab-3ea3219a1aef.png)
The red box is the actual content which would be rendered in `body` if the extension is turned off

The code that does this can be seen here https://github.com/mjbvz/vscode-github-markdown-preview-style/blob/f2cb247f3e4094f729642b62d142b71aac5a3a08/dist/extension.js#L43-L47

**Comment by seamusm02** [comment]
Yup, that works!  Thanks!
